import type { LocaleTag } from "@/lib/i18n/config";
export const workspaceCopy: Record<LocaleTag, Record<string, string>> = {
  "en-GB": {
    overview: "Overview",
    library: "My library",
    create: "Create a reading",
    charts: "Birth charts",
    membership: "Membership",
    settings: "Settings",
    access: "Your available access",
    adminAccess: "Administrator access · Premium features",
    accountIncluded: "Included with your account",
    grantAccess: "Complimentary access",
    planIncluded: "Included in your plan",
    notIncluded: "Not included in your plan",
    unavailable: "Temporarily unavailable",
    credits: "Unused report credits",
    purchases: "Unused report purchases",
    recent: "Recent saved work",
    viewAll: "View all saved work",
    daily: "Daily readings",
    weekly: "Weekly readings",
    reports: "Detailed reports",
    all: "All saved work",
    empty: "No saved readings yet. Create a reading to begin your library.",
    gettingStarted: "Getting started",
    guide:
      "Save your birth chart, choose a reading, then return to My library to find it.",
    explore: "Explore reports",
    saved: "Saved readings",
    open: "Open",
    until: "Available until",
    created: "Created",
    accessDetails: "Access details",
    billingExplanation:
      "Your billing plan and additional access are shown separately.",
    weeklyRemaining: "New weekly readings remaining",
    resets: "Resets",
  },
  "es-ES": {
    overview: "Resumen",
    library: "Mi biblioteca",
    create: "Crear una lectura",
    charts: "Cartas natales",
    membership: "Membresía",
    settings: "Ajustes",
    access: "Tu acceso disponible",
    adminAccess: "Acceso de administrador · Funciones Premium",
    accountIncluded: "Incluido con tu cuenta",
    grantAccess: "Acceso de cortesía",
    planIncluded: "Incluido en tu plan",
    notIncluded: "No incluido en tu plan",
    unavailable: "No disponible temporalmente",
    credits: "Créditos de informes sin usar",
    purchases: "Informes comprados sin usar",
    recent: "Contenido guardado reciente",
    viewAll: "Ver todo el contenido guardado",
    daily: "Lecturas diarias",
    weekly: "Lecturas semanales",
    reports: "Informes detallados",
    all: "Todo lo guardado",
    empty: "Aún no hay lecturas guardadas. Crea una lectura para comenzar.",
    gettingStarted: "Primeros pasos",
    guide:
      "Guarda tu carta natal, elige una lectura y vuelve a Mi biblioteca para encontrarla.",
    explore: "Explorar informes",
    saved: "Lecturas guardadas",
    open: "Abrir",
    until: "Disponible hasta",
    created: "Creado",
    accessDetails: "Detalles de acceso",
    billingExplanation:
      "Tu plan de facturación y el acceso adicional se muestran por separado.",
    weeklyRemaining: "Lecturas semanales nuevas restantes",
    resets: "Se restablece",
  },
  "fr-FR": {
    overview: "Aperçu",
    library: "Ma bibliothèque",
    create: "Créer une lecture",
    charts: "Thèmes natals",
    membership: "Abonnement",
    settings: "Réglages",
    access: "Vos accès disponibles",
    adminAccess: "Accès administrateur · Fonctions Premium",
    accountIncluded: "Inclus avec votre compte",
    grantAccess: "Accès offert",
    planIncluded: "Inclus dans votre formule",
    notIncluded: "Non inclus dans votre formule",
    unavailable: "Temporairement indisponible",
    credits: "Crédits de rapports inutilisés",
    purchases: "Rapports achetés inutilisés",
    recent: "Dernières lectures enregistrées",
    viewAll: "Voir toutes les lectures",
    daily: "Lectures quotidiennes",
    weekly: "Lectures hebdomadaires",
    reports: "Rapports détaillés",
    all: "Toutes les lectures",
    empty: "Aucune lecture enregistrée. Créez une lecture pour commencer.",
    gettingStarted: "Premiers pas",
    guide:
      "Enregistrez votre thème natal, choisissez une lecture, puis retrouvez-la dans Ma bibliothèque.",
    explore: "Explorer les rapports",
    saved: "Lectures enregistrées",
    open: "Ouvrir",
    until: "Disponible jusqu’au",
    created: "Créé",
    accessDetails: "Détails des accès",
    billingExplanation:
      "Votre formule de facturation et vos accès supplémentaires sont affichés séparément.",
    weeklyRemaining: "Nouvelles lectures hebdomadaires restantes",
    resets: "Renouvellement",
  },
  "de-DE": {
    overview: "Übersicht",
    library: "Meine Bibliothek",
    create: "Lesung erstellen",
    charts: "Geburtshoroskope",
    membership: "Mitgliedschaft",
    settings: "Einstellungen",
    access: "Deine verfügbaren Zugänge",
    adminAccess: "Administratorzugang · Premium-Funktionen",
    accountIncluded: "In deinem Konto enthalten",
    grantAccess: "Zusätzlicher kostenloser Zugang",
    planIncluded: "In deinem Plan enthalten",
    notIncluded: "Nicht in deinem Plan enthalten",
    unavailable: "Vorübergehend nicht verfügbar",
    credits: "Ungenutzte Berichtsguthaben",
    purchases: "Ungenutzte Berichtskäufe",
    recent: "Zuletzt gespeicherte Lesungen",
    viewAll: "Alle gespeicherten Lesungen",
    daily: "Tageslesungen",
    weekly: "Wochenlesungen",
    reports: "Ausführliche Berichte",
    all: "Alle Lesungen",
    empty: "Noch keine gespeicherten Lesungen. Erstelle deine erste Lesung.",
    gettingStarted: "Erste Schritte",
    guide:
      "Speichere dein Geburtshoroskop, wähle eine Lesung und finde sie in Meine Bibliothek wieder.",
    explore: "Berichte entdecken",
    saved: "Gespeicherte Lesungen",
    open: "Öffnen",
    until: "Verfügbar bis",
    created: "Erstellt",
    accessDetails: "Zugangsdetails",
    billingExplanation:
      "Dein Abrechnungsplan und zusätzliche Zugänge werden getrennt angezeigt.",
    weeklyRemaining: "Verbleibende neue Wochenlesungen",
    resets: "Wird zurückgesetzt am",
  },
};
